name: swift_server
description: Simple microservices framework using swift_composer.
  Create servers, daemons and cli tools with a layer to access mysql db, amqp and files.
  Used by https://swift.shop
version: 0.3.0
homepage: https://github.com/coffee-software/swift_server
environment:
  sdk: ^3.10.0
dependencies:
  swift_composer: ^0.9.0
  yaml: ^3.1.3
  mysql_client_plus: ^0.1.2
  dart_amqp: ^0.3.1
  args: ^2.7.0
  mailer: ^6.6.0
  redis: ^4.0.0
  path: ^1.9.1
  influxdb_client: ^2.11.0
dev_dependencies:
  lints: ^6.0.0
  test: any
  build_runner: any
